### ISSUE TITLE
Could not find function "getAnnot"

### ISSUE THREAD

**Issue by BastiDucreux** [reese3928/methylGSA#2]
Hi,

I'm currently trying to use the getAnnot function but it tells me the function is impossible to find :
> library(methylGSA)
> a=getAnnot("EPIC")
Error in getAnnot("EPIC") : could not find function "getAnnot"

> packageVersion('methylGSA')
[1] ‘1.8.0’

Would you know where the problem comes from ?

Thanks in advance.

Bastien

**Comment by reese3928** [comment]
Hi, 

This is because `getAnnot()` is an internal function and it is not exported. If this internal function has to be used. We can try:
```
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(methylGSA)
a = methylGSA:::getAnnot("EPIC")
```

Xu
